### ISSUE TITLE
Unable to remove annotation when wildcard import is used

### ISSUE THREAD

**Issue by mizdebsk** [fedora-java/jurand#3]
I have the following class:
```
import java.lang.annotation.*;
@Retention(RetentionPolicy.CLASS)
@Target(ElementType.METHOD)
public @interface MyAnnotation {
}
```
I want to remove Retention annotation, but I can't do that with Jurand.
None of the calls I tried worked.
What arguments should I pass to Jurand to remove Retention?

**Comment by mkoncek** [comment]
You need to specify `-a` to also remove annotations found in code. Without `-a` it only removes import statements. Wildcard import should not prevent it from working. It only prevents associating the FQN with the simple name of the symbol. But it is still possible to specify matchers to match what you want. When you remove imports by pattern and specify `-a`, the tool also attempts to remove all annotations whose imports were removed even if they would not match by the pattern.

For matching `Retention` only:
`$ jurand MyAnnotation.java -a -n Retention` or
`$ jurand MyAnnotation.java -a -p Retention`

For matching the import:
`$ jurand MyAnnotation.java -p [*]` or
`$ jurand MyAnnotation.java -p annotation[.][*]` or
`$ jurand MyAnnotation.java -p annotation\.\*`

These flags can be merged.

Note that `-n '*'` does not match anything because `*` is not a simple class name. Wildcard imports can only be matched with `-p`.
